### PR TITLE
Make Sprite data pretty

### PR DESCRIPTION
**Pull request by ace-dent**
Improve appearance of sprite data for easier editing.
- Characters are more searchable by adding descriptive text and ASCII code.
- Visual representation of images and bit layout.

### CODE REVIEW

**Comment by BotiKis** [comment]
@ace-dent Very cool, thank you.
Somehow the visual representation is turned 90° clockwise. Can you fix that before merging?

**Comment by ace-dent** [comment]
@yinkou - thanks for reviewing it! :smile:
The 90° rotation is kinda the point!... This is the exact way the data is stored, so your code can write it to the screen buffer as quickly as possible. You've also squeezed in two glyphs per byte, which is unusual. So there's quite some complexity there... hence my extensive annotations.

For a newcomer (like me!), it is difficult to understand / visualise how an image relates to a bitfield (and then a hex byte value). You can check yourself: the byte value > binary array > image. I don't think it's worth adding the images as they are viewed (unrotated) to the code, as you already provide a preview png image for the set.

I'm hoping these annotations make it clearer, to encourage understanding, use and editing of your font.

**Comment by BotiKis** [comment]
> @yinkou - thanks for reviewing it! 😄
> The 90° rotation is kinda the point!... This is the exact way the data is stored, so your code can write it to the screen buffer as quickly as possible.

Ah I understand, makes sense.

> You've also squeezed in two glyphs per byte, which is unusual. So there's quite some complexity there... hence my extensive annotations.
It's unusual but also quite intended. This save some space :).

> I'm hoping these annotations make it clearer, to encourage understanding, use and editing of your font.
I believe that too!

**Comment by BotiKis** [comment]
I just looked at the code and tbh I can't remember why I was doing it like this... 😅

**Comment by ace-dent** [comment]
Nice. Thanks for merging ! 😃

**Pull request merged**
